version: '3'

services:
  LVAService:
    image: mariadb
    container_name: LVAServiceDB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounting init SQL file

  keycloak:
    image: keycloak/keycloak
    container_name: LVAServiceKeycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    #entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm''